import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1600px] m-auto">
          <nav class="bg-base-200">
            <div class="navbar px-40">
              <div class="navbar-center flex lg:flex-1">
                <ul class="menu menu-vertical">
                  <li>
                    <a class="capitalize active" href="/" aria-current="page">
                      home
                    </a>
                  </li>
                  <li>
                    <a class="capitalize" href="/about">
                      about
                    </a>
                  </li>
                  <li>
                    <a class="capitalize" href="/products">
                      products
                    </a>
                  </li>
                  <li>
                    <a class="capitalize" href="/cart">
                      cart
                    </a>
                  </li>
                </ul>
              </div>
             
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
